### ISSUE TITLE
plans to expand

### ISSUE THREAD

**Issue by bwkam** [amedoeyes/eyes.nvim#1]
hello, I've loved this theme, right amount of monochrome I was looking for. I was wondering if there are plans to expand it into more applications and frameworks, like GTK or Qt. I'd be happy to help if you were up for it.

**Comment by amedoeyes** [comment]
Thanks! glad you liked it. You can check my [dotfiles](https://github.com/amedoeyes/dotfiles) for more monochrome themes, here are the ones for GTK and QT, I haven't really put much thought into the GTK one because it's a pain lol. Also I'm using breeze-gtk.
https://github.com/amedoeyes/dotfiles/blob/master/.config/gtk-3.0/gtk.css
https://github.com/amedoeyes/dotfiles/blob/master/.config/qt5ct/colors/Eyes.conf

**Comment by bwkam** [comment]
Thanks, those look good too. I'll close this :+1:
